<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "advantage".
 *
 * @property integer $id
 * @property string $images
 * @property string $text
 * @property string $text_ru
 */
class Advantage extends Img
{

    public $imageIcons;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'advantage';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            [['text', 'text_ru'], 'string', 'max' => 50],
            [['imageIcons'], 'file', 'extensions' => 'png, jpg, svg, gif'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',

            'text' => 'Text[Ua]',
            'text_ru' => 'Text[Ru]',
            'imageIcons' => 'Картинка (Рекомендуемый размер 110х110рх)',

        ];
    }

    public function beforeSave($insert)
    {
        $this->imageIcons = UploadedFile::getInstance( $this, 'imageIcons');

        if($this->images==null){
            $this->images = [
                "imageIcons"=>"",

            ];
            $this->images = json_encode($this->images);
            $this->images = json_decode($this->images);
        }

        if($this->imageIcons){
            $name =  $this->generateName() . '.' . $this->imageIcons->extension;
            $this->imageIcons->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->images->imageIcons = $name;
        }

        $this->images = json_encode($this->images);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->images = json_decode($this->images);
        if(Yii::$app->language=='ru'){
            $this->text = $this->text_ru;

        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }





}
