<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "slider".
 *
 * @property integer $id
 * @property string $title
 * @property string $title_ru
 * @property string $description
 * @property string $description_ru
 * @property string $images
 */
class Slider extends Img
{
    public $sliderImage;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'slider';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sliderImage'], 'file', 'extensions' => 'png, jpg, svg, gif'],
            [['description', 'description_ru'], 'string'],
            [['title', 'title_ru'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'title_ru' => 'Title Ru',
            'description' => 'Description',
            'description_ru' => 'Description Ru',
            'sliderImage' => 'Images',
        ];
    }


    public function beforeSave($insert)
    {
        $this->sliderImage = UploadedFile::getInstance( $this, 'sliderImage');
        if($this->images==null){
            $this->images = [
                "sliderImage"=>"",

            ];
            $this->images = json_encode($this->images);
            $this->images = json_decode($this->images);
        }

        if($this->sliderImage){
            $name =  $this->generateName() . '.' . $this->sliderImage->extension;
            $this->sliderImage->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->images->sliderImage = $name;
        }


        $this->images = json_encode($this->images);


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->images = json_decode($this->images);

        parent::afterFind(); // TODO: Change the autogenerated stub
    }



}
