<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "store".
 *
 * @property integer $id
 * @property string $name
 * @property string $shop_link
 * @property string $images
 */
class Store extends Img
{
    public $logo_store;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'store';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['logo_store'], 'file', 'extensions' => 'png, jpg, svg, gif'],
            [['name', 'shop_link'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'shop_link' => 'Shop Link',
            'logo_store' => 'Images',
        ];
    }

    public function beforeSave($insert)
    {
        $this->logo_store = UploadedFile::getInstance( $this, 'logo_store');
        if($this->images==null){
            $this->images = [
                "logo_store"=>"",

            ];
            $this->images = json_encode($this->images);
            $this->images = json_decode($this->images);
        }

        if($this->logo_store){
            $name =  $this->generateName() . '.' . $this->logo_store->extension;
            $this->logo_store->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->images->logo_store = $name;
        }


        $this->images = json_encode($this->images);


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->images = json_decode($this->images);

        parent::afterFind(); // TODO: Change the autogenerated stub
    }
    
}
