<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "video_index".
 *
 * @property integer $id
 * @property string $video_link
 * @property string $images
 */
class VideoIndex extends Img
{
    public $img;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'video_index';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['img'], 'file', 'extensions' => 'png, jpg, svg, gif'],
            [['video_link'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'video_link' => 'Ccылка на видео',
            'img' => 'Фон под кнопкой плей',
        ];
    }

    public function beforeSave($insert)
    {
        $this->img = UploadedFile::getInstance( $this, 'img');
        if($this->images==null){
            $this->images = [
                "img"=>"",

            ];
            $this->images = json_encode($this->images);
            $this->images = json_decode($this->images);
        }

        if($this->img){
            $name =  $this->generateName() . '.' . $this->img->extension;
            $this->img->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->images->img = $name;
        }


        $this->images = json_encode($this->images);


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->images = json_decode($this->images);

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

}
